### ISSUE TITLE
Moodle Integration

### ISSUE THREAD

**Issue by onebonsai** [longhornopen/laravel-celtic-lti#13]
Hi!

Thanks for an excellent plugin to Laravel with the LTI 1.3 support. I am trying to get this to work. I am absolutely not fluent in LTI and how it is setup. I would like to achieve the following:

1/ In an LMS that supports LTI 1.3 (eg Moodle) add our tool
2/ This tool should be a page on our website with some information relevant to the current user
3/ Once the user finishes what needs be done on our site, the result (course complete) will be sent back to the LMS

To achieve this, I have added a tool in Moodle (Site Admin | Plugins | Manage Tools). I used the manual config and provided the URLs to the routes that you provided:

https://[domain]/lti
and
https://[domain]/lti/jwks

I saved this and then I took note of the Tool configuration details, such as Platform ID, Clinet ID and Deployment ID.

I manually created a record in the database, including this information.

`
INSERT INTO `lti2_consumer` (`consumer_pk`, `name`, `consumer_key`, `secret`, `platform_id`, `client_id`, `deployment_id`, `public_key`, `lti_version`, `signature_method`, `consumer_name`, `consumer_version`, `consumer_guid`, `profile`, `tool_proxy`, `settings`, `protected`, `enabled`, `enable_from`, `enable_until`, `last_access`, `created`, `updated`) VALUES
(1, 'https://moodle.DOMAIN.com', NULL, NULL, 'https://moodle.DOMAIN.com', 'XXX', '2', 'XXX', '1.3', 'RS256', NULL, NULL, NULL, NULL, NULL, '{\"_authentication_request_url\":\"https:\\/\\/moodle.DOMAIN.com\\/mod\\/lti\\/auth.php\",\"_oauth2_access_token_url\":\"https:\\/\\/moodle.DOMAIN.com\\/mod\\/lti\\/token.php\",\"_jku\":\"https:\\/\\/moodle.DOMAIN.com\\/mod\\/lti\\/certs.php\"}', 0, 1, NULL, NULL, NULL, '2023-08-10 22:47:11', '2023-08-10 22:47:11');
`

Now, I try to add the tool to a course and click it to launch it. I however get an error:
`Platform not found or no platform authentication request URL.`

Indeed, the $tool does not contain much data.

It does not seem that the platform information is loaded from the database. What am I missing? I probably misunderstood how to set this up properly...

Thanks a lot for any insights already!

**Comment by chrispittman** [comment]
This error is coming from the CeLTIc LTI library, which this project is a thin wrapper around: https://github.com/celtic-project/LTI-PHP/blob/57c4b82a1d602a975a50572e1971aed5c8898edf/src/Tool.php#L2046-L2064

You can see that it's looking for HTTP parameters in the request from Moodle that are named 'iss', 'client_id', and 'lti_deployment_id', and that those should match what are in the 'platform_id', 'client_id', and 'deployment_id' columns in the database, respectively.  Can you confirm whether or not that's happening?

**Comment by onebonsai** [comment]
Thanks! Using your input, I think I found out what is causing the issue.

We are using the tool in a multi-tenant database structure. LtiTool uses a dataConnector that connects through getPdo() to the database. It seems it connects to the master database not the tenant database. 

I will have a look how to fix this minimally invasive :-)

Thanks!!

**Comment by onebonsai** [comment]
> Version 0.5.0 will allow you to pass one of CeLTIc's DataConnector objects to Tool::getLtiTool(). That should get you going, but please comment if not.

Hi Thanks for that option!

I already adjusted the code to do just that. However, it does not seem to function as expected. I must admit that I am not familiar with pdo, as we mostly use standard Eloquent etc.

I use this code. 

`
    public function ltiMessage(Request $request) {
        $tenantConnection = tenant()->database()->connection();
        $host = $tenantConnection['host'];
        $dbname = $tenantConnection['database'];
        $username = $tenantConnection['username'];
        $password = $tenantConnection['password'];

        $pdo = new PDO("mysql:host=$host;dbname=$dbname", $username, $password);

        $dataConnector = DataConnector::getDataConnector($pdo, '', 'mysql');

        $tool = LtiTool::getLtiTool($dataConnector);
        dd($tool);

        $tool->handleRequest();


        if ($tool->getLaunchType() === $tool::LAUNCH_TYPE_LAUNCH) {

            echo $tool->userResult->firstname;

            dd($tool);
        }
    }
`

I would expect that this will actually connect to the database I provide to the $pdo. However, it still connects to the original.

I adjusted your code base:

`
public static function getLtiTool($dataConnector = null) {
        // Disable dependence on a draft LTI spec that currently causes problems in Canvas
        // https://github.com/celtic-project/LTI-PHP/issues/46
        parent::$postMessageTimeoutDelay = -1;

        if (self::$singleton_tool === null) {
            self::$singleton_tool = new LtiTool($dataConnector);
        }
        return self::$singleton_tool;
    }
`

The idea is that I can connect to the tenant database, which I know from the $tenantConnection object. Then I pass the required info to the $pdo which I put in the $dataConnector. I would then expect all to work on that tenant database and function as normal.

Maybe you see something I do wrong?

Thanks!

**Comment by chrispittman** [comment]
If you're using Eloquent, I'm assuming you're doing something like:
`DB::connection('name_of_tenant')->select(....)`
If so, the PDO object should be accessible by `DB::connection('name_of_tenant')->getPdo()`.  You don't have to build your own PDO object from scratch.

**Comment by onebonsai** [comment]
Sadly that does not work...

I tried the following:

`$tenant = tenant();
$tenant->run(function() {
$name = DB::connection()->getDatabaseName();
//dd($name);
$pdo = DB::connection()->getPdo();
$dataConnector = DataConnector::getDataConnector($pdo, '', 'pdo')
//dd($dataConnector);
$tool = LtiTool::getLtiTool($dataConnector);
$tool->handleRequest();
dd($tool);
});`

$name becomes the DB name of the tenant. $dataConnector is unclear if it connects to the tenant. $tool clearly points to the central database instead of the tenant DB.

I am using stancl tenancy: https://tenancyforlaravel.com

What I suspect is that PDO is unable to distinguish the tenant database and defaults to the central one.

Maybe you have a better insight into how PDO is used in the laravel-celtic? It might very well be an issue with the tenancy system and unrelated to laravel-celtic, but it can also be that the specific way the PDO is used, it always reverts back to a default connection...

**Comment by onebonsai** [comment]
OK, I found how I can fix this issue :-)

In DataConnector_pdo | loadPlatform, the queries query the central database. Altering the $sql to point to the tenant database would effectively fix the issue. However, this would require some significant adjustments to the code base of the ceLTIc DataConnector system. 

`                $sql = 'SELECT consumer_pk, name, consumer_key, secret, ' .
                    'platform_id, client_id, deployment_id, public_key, ' .
                    'lti_version, signature_method, consumer_name, consumer_version, consumer_guid, ' .
                    'profile, tool_proxy, settings, protected, enabled, ' .
                    'enable_from, enable_until, last_access, created, updated ' .
                    "FROM {$this->dbTableNamePrefix}" . static::PLATFORM_TABLE_NAME . ' ' .
                    'WHERE (platform_id = :platform_id) AND (client_id = :client_id) AND (deployment_id = :deployment_id)';`

becomes

`                $sql = 'SELECT consumer_pk, name, consumer_key, secret, ' .
                    'platform_id, client_id, deployment_id, public_key, ' .
                    'lti_version, signature_method, consumer_name, consumer_version, consumer_guid, ' .
                    'profile, tool_proxy, settings, protected, enabled, ' .
                    'enable_from, enable_until, last_access, created, updated ' .
                    "FROM {$this->dbName}.{$this->dbTableNamePrefix}" . static::PLATFORM_TABLE_NAME . ' ' .
                    'WHERE (platform_id = :platform_id) AND (client_id = :client_id) AND (deployment_id = :deployment_id)';`

$this->dbName would have to be set separately. It remains weird that DataConnector does not take the tenant's database. If so, this all would not be required...

**Comment by onebonsai** [comment]
I was able to figure out a solution that required no changes to the ceLTIc or longhornopen code:

`    public function ltiMessage(Request $request) {
        $pdo = DB::connection()->getPdo();
        $dataConnector = DataConnector::getDataConnector($pdo, 'tenant_DatabaseName.', 'pdo');

        $tool = new LtiTool($dataConnector);
        LtiTool::$postMessageTimeoutDelay = -1;

        $tool->handleRequest();

        if ($tool->getLaunchType() === $tool::LAUNCH_TYPE_LAUNCH) {
            /*
            At this point:
              $tool->platform describes the platform (LMS)
              $tool->context describes the context (course)
              $tool->resourceLink describes the resourceLink (tool placement in course)
              $tool->userResult describes the user.

            Each of these has a getRecordId() function which returns a database primary key.
            Store these keys in a session or in your app's database for later lookup.
            If your app has database tables corresponding to courses, users, etc you can store this primary key in that table.
            */

            dd($tool);
        }
    }`

I basically use the prefix parameter to also set the database name.

This way, all code in the loadPlatform will revert back to the correct database, and all is well :-)

Thanks a lot for your help and pointers in the right direction!
