### ISSUE TITLE
Send Outcome back to LMS

### ISSUE THREAD

**Issue by onebonsai** [longhornopen/laravel-celtic-lti#14]
I have the connection running between an LMS (in my case Moodle) and my Tool. 

The idea is that the Tool will send back a grade to the LMS after the student finishes the course. I understand from the examples from ceLTIc that this is possible, but the exact way how to achieve it remains a bit unclear using the Longhornopen wrapper.

Currently, I have a separate function that is called by an API that will handle sending back the grade to the LMS. This function is as follows:

public function updateOutcome(Request $request) {

        $pdo = DB::connection()->getPdo();
        $databaseConfig = tenant()->database();
        $dbName = $databaseConfig->getName();
        $dataConnector = DataConnector::getDataConnector($pdo, $dbName.'.', 'pdo');
        $employee = Employee::where('uid', '=', $request['uid'])->first();

        $user = UserResult::fromRecordId($employee->lms_user_id, $dataConnector);
        $resourceLink = ResourceLink::fromRecordId($user->getResourceLink()->getRecordId(), $dataConnector);

        $outcome = new Outcome(0.63);
        $outcome->comment = 'Good work!';
        $ok = $resourceLink->doOutcomesService(ResourceLink::EXT_WRITE, $outcome, $user);
        $score = -1;
        if ($resourceLink->doOutcomesService(ResourceLink::EXT_READ, $outcome, $user)) {
            $score = $outcome->getValue();
        }
        return $score;
    }

In this test function, I first set the $outcome and then read it back. I would expect $score to be 0.63, but it is -1, pointing to a failure to read the $outcome from the service.

I retrieve the employee, which has stored in it the $tool->userResult->getRecordId(). The $user is retrieved from the DB, as well as the linked $resourceLink. 

Next, using the $resourceLink, I send a doOutcomesService to the LMS to update the outcome.

When I check all objects, I however see that $resourceLink does not have a $platform defined. I think that this is the cause why the outcome is not sent to the platform. 

As far as I can see, the information in the database is stored automatically in the ltiMessage function. However, it seems that the platform information is not linked to the resourceLink? 

Am I using the correct methods to send back this outcome/grading?

**Comment by onebonsai** [comment]
Also maybe not unimportant. The way I am building this, is that one uses a website to start a session in Moodle (the Tool will point to a website). Then, after some time, in another webservice, the grading is sent to the Moodle Server. 

As such, any information stored in SESSION will not be available at that point. I think the tool should therefore first be initialized and then we should build the $user, $resourceLink and $platform from data stored in the database. 

Given that the $resourceLink is not linked to the consumer / platform in my database, I am unsure if this actually will be possible.

At least, this is with my limited understanding of LTI 1.3. Maybe I am overcomplicating things?

**Comment by chrispittman** [comment]
(We don't hide any of the underlying CeLTIc objects; this library just tries to provide easier access to them in Laravel projects.  So if you have detailed questions about how CeLTIc works, that project can answer you better than we can.)

LTI 1.3 defines a set of URIs defining the services that the LMS offers; the service you're calling is one of them.  Check to make sure that you've set the appropriate URIs in the `required_scopes` section in config/lti.php.  Also check to make sure that your tool installation in Moodle is set up to allow access to the service you're calling.  (Reading a score and writing it may be separate permissions in Moodle.)

In my own apps that send scores back successfully to Canvas, the `lti2_resource_link` table has values for `resource_link_pk` and `context_pk`, but `consumer_pk` is null.  `settings` is a JSON block that contains the URL that scores are supposed to be sent to.  The `lti2_user_result` table contains the user-specific key that identifies the user when that URL is called.  To my knowledge, that should be all you need.  Sessions are not required to send a score back; everything you need is in the database after Tool::handleRequest() is called.

**Comment by onebonsai** [comment]
Thanks for confirming the database contents! 

As I understand, required_scopes should be viewed as permissions rather than real URLs to some endpoints? I enable them as such:
`
'required_scopes' => [

            // sample scope URLs
            "https://purl.imsglobal.org/spec/lti-ags/scope/lineitem",
            "https://purl.imsglobal.org/spec/lti-ags/scope/result.readonly",
            "https://purl.imsglobal.org/spec/lti-ags/scope/score",
            //"https://purl.imsglobal.org/spec/lti-nrps/scope/contextmembership.readonly",
        ]
`

All the records in the tables are similar to what you mention. You mention however that `settings` contains the URL to send the score to, but should that JSON be in a specific format? I mean, what is the parameter name of that URL?

I now have this function:
`    public function updateOutcome(Request $request)

    {
        $tool = $this->getLtiTool();
        $user = $tool->getUserResultById($user_uid);
        $resourceLink = $tool->getResourceLinkById($user->getResourceLink()->getRecordId());

        // up to here all seems to be working correctly

        $outcome = new Outcome(0.63);
        $outcome->comment = 'Good work!';
        $ok = $resourceLink->doOutcomesService(ResourceLink::EXT_WRITE, $outcome, $user);
        $score = -1;
        if ($resourceLink->doOutcomesService(ResourceLink::EXT_READ, $outcome, $user)) {
            $score = $outcome->getValue();
        }
        return $score;
    }
`

Does this seem correct to you? I think I already enabled scoring in Moodle, but also there I am figuring out things as we speak.

Sorry again for all the noob questions!

**Comment by chrispittman** [comment]
Yes, `required_scopes` are URIs identifying permissions, not URLs you're supposed to connect to.

CeLTIc's `ResourceLink::hasOutcomesService()` details the `settings` keys that it's looking for.  You may just want to try calling hasOutcomesService() yourself and see what answer it gives.

**Comment by onebonsai** [comment]
Thanks for checking!

`ResourceLink::hasOutcomesService()` returns false, and `settings` is `[]`. I think I need to add `custom_lineitem_url` and `custom_ags_scopes` to the settings. Not sure how to add these, except manually in the database. Also not sure what to use as values, as Moodle documentation is not particularly helpful on that part...

I have posted a question on both Moodle and CeLTIc. You are right that this is more of their responsibilities. Your help was really appreciated though!

**Comment by onebonsai** [comment]
I figured out at least on the Moodle side how to set `custom_lineitems_url`. This is a setting hidden in the Tool Settings page under `IMS LTI Assignment and Grade Services`. Once set, the `custom_lineitems_url` setting is populated and `hasOutcomesService` at least returns something.

However, we need `custom_lineitem_url` (note the singular), as this is required for the `doOutcomesService` function... That must be yet another hidden setting in Moodle that specifically sets that...

I feel a bit like Sherlock at the moment :-)

**Comment by onebonsai** [comment]
Just to let you know: I figured out where the setting was in Moodle. It was a bit tucked away, but now the settings does mention `custom_lineitem_url`. 

Now, sadly, when I run doOutcomesService in the ltiMessage at launch, I get a 401 Unauthorized back. Not sure where I should set the authorization code (and which) as the bearer and public - private key are all set up...  I asked on the CeLTIc forum, hopefully they can help with that!

Thanks again for all the input and help!
