### ISSUE TITLE
Platform or Tool

### ISSUE THREAD

**Issue by Stunext** [longhornopen/laravel-celtic-lti#16]
I have created my own LMS and have been little by little adding standard features of this type of application. I am currently looking to add the LTI option. In this case my intention is to act as a "platform" to make use of "tools" such as LinkedinElearning and H5P. In this case, will this library and the implementation example you have posted allow me to act as a "platform"?

**Comment by chrispittman** [comment]
This library's really geared towards Tool development.  If you're looking
to build a Platform, consider using the underlying CeLTIc libraries
directly.
