### ISSUE TITLE
Unable to install on Laravel 7.8

### ISSUE THREAD

**Issue by ahsan-gill** [longhornopen/laravel-celtic-lti#2]

**Comment by ahsan-gill** [comment]
I get following error messages:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for longhornopen/laravel-celtic-lti ^0.2.3 -> satisfiable by longhornopen/laravel-celtic-lti[v0.2.3].
    - Conclusion: remove laravel/framework v7.8.1
    - Conclusion: don't install laravel/framework v7.8.1
    - longhornopen/laravel-celtic-lti v0.2.3 requires illuminate/support ^8 -> satisfiable by laravel/framework[8.x-dev], illuminate/support[8.x-dev, v8.0.0, v8.0.1, v8.0.2, v8.0.3, v8.0.4, v8.1.0, v8.10.0, v8.11.0, v8.11.1, v8.11.2, v8.12.0, v8.12.1, v8.12.2, v8.12.3, v8.13.0, v8.14.0, v8.15.0, v8.16.0, v8.16.1, v8.17.0, v8.17.2, v8.18.0, v8.18.1, v8.19.0, v8.2.0, v8.20.0, v8.20.1, v8.21.0, v8.22.0, v8.22.1, v8.23.1, v8.24.0, v8.25.0, v8.26.0, v8.26.1, v8.27.0, v8.28.0, v8.28.1, v8.29.0, v8.3.0, v8.30.0, v8.30.1, v8.31.0, v8.32.0, v8.32.1, v8.33.0, v8.33.1, v8.34.0, v8.35.0, v8.35.1, v8.36.0, v8.36.1, v8.36.2, v8.37.0, v8.38.0, v8.39.0, v8.4.0, v8.40.0, v8.41.0, v8.42.0, v8.42.1, v8.43.0, v8.44.0, v8.45.0, v8.45.1, v8.46.0, v8.47.0, v8.48.0, v8.48.1, v8.48.2, v8.49.0, v8.49.1, v8.49.2, v8.5.0, v8.50.0, v8.51.0, v8.52.0, v8.53.0, v8.53.1, v8.54.0, v8.55.0, v8.56.0, v8.57.0, v8.58.0, v8.59.0, v8.6.0, v8.60.0, v8.61.0, v8.62.0, v8.63.0, v8.64.0, v8.65.0, v8.66.0, v8.67.0, v8.68.0, v8.68.1, v8.69.0, v8.7.0, v8.7.1, v8.70.0, v8.70.1, v8.70.2, v8.71.0, v8.72.0, v8.73.0, v8.73.1, v8.73.2, v8.74.0, v8.75.0, v8.8.0, v8.9.0].
    - Can only install one of: laravel/framework[8.x-dev, v7.8.1].

**Comment by chrispittman** [comment]
Laravel 7 is end-of-life, but I think we should work fine there.  I just published version 0.2.4, which should allow usage on Laravel 7.  Let us know if you have any problems!

**Comment by adydev15** [comment]
Hi @chrispittman 

what version will be used for Laravel 6.. ?

This package you have created for Celtic LTI for larave right .. ?

Does it also extends the support for LTI 1.1 as well ??

**Comment by chrispittman** [comment]
Laravel 6 is now [end-of-life](https://laravelversions.com/en).  You should really look at upgrading to Laravel 8 or 9 at this point, in my opinion.  [Here's the file listing the versions of Laravel we're tested against](https://github.com/longhornopen/laravel-celtic-lti/blob/8a3d7995a1f888a99724c0d05780d1065e3b2338/composer.json#L10), if you'd like to fork this repo to add Laravel 6 support.

LTI 1.1 shouldn't be a problem - all our tools that say 'LTI 1.2' should work for 1.1 as well.

**Comment by adydev15** [comment]
Hi @chrispittman 

Thanks for explanation i would've done it if that was my project as there are certain other dependencies with project so i cant take decision solely.

I was hoping to have support for Laravel 6.

Thanks

**Comment by chrispittman** [comment]
We're not gonna have time to test a Laravel 6 version of this anytime soon, but if you'd like to fork the repo, add Laravel 6 support, and run it through some simple tests, we'd be glad to consider a pull request with those changes.

**Comment by adydev15** [comment]
Right now i am also occupied but will definitely do somewhat later when i will have some spare time to give support devs like me :) 

Thanks !
