### ISSUE TITLE
Connectivity with Schoology LTI 1.3 app.

### ISSUE THREAD

**Issue by usmantariqpaktolus** [longhornopen/laravel-celtic-lti#23]
We didn't be able to connect with Schoology "Type of App" --> LTI 1.3 App. 
I want to connect with Schoology "Type of App" LTI 1.3 App and then want to retrieve user details.

For you information: I am working on Laravel App.

**Comment by chrispittman** [comment]
Hi.  Can you be specific about what your problem is?

**Comment by usmantariqpaktolus** [comment]
I am using Laravel . and I want to connect with Schoology LTI 1.3 app. 
can you please provide me with the code to connect Laravel to  LTI1.3 Schoology app.
Also please let me know what to add in configuration on APP. I am sending you the screenshot of my Application configuration
![image](https://github.com/longhornopen/laravel-celtic-lti/assets/110023967/0ae0df03-3846-44d7-a338-5c6909f547ab)
Thankyou very much for your guidance and support.

**Comment by usmantariqpaktolus** [comment]
We are using your application.
 https://github.com/longhornopen/lti-example-app

**Comment by chrispittman** [comment]
Try using 'http://127.0.0.1:8000/lti' for both the 'Domain/URL' and the 'Redirect URL'.

**Comment by usmantariqpaktolus** [comment]
Now schoology app configuration looks like
![image](https://github.com/longhornopen/laravel-celtic-lti/assets/110023967/765f846e-eee4-40cc-8777-082cbb1126f5)
and on opening the app 
it is giving me information
![image](https://github.com/longhornopen/laravel-celtic-lti/assets/110023967/476d3521-4405-496d-9744-7f1c9a57241e)
I want to do authentication from schoology "lit app 1.3" and get user details.
please advise me changes that need to be done in 
(http://127.0.0.1:8000/my_app_home)route function

**Comment by chrispittman** [comment]
There's an example, under "Add the LtiController::ltiMessage function", at https://github.com/longhornopen/laravel-celtic-lti/wiki/Laravel-app-setup
