### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by ernst77** [longhornopen/laravel-celtic-lti#26]
When I just install, post install composer hooks don't work and it locks whole package due missing config.

<img width="833" alt="image" src="https://github.com/longhornopen/laravel-celtic-lti/assets/17262977/b5870712-e0d8-4ac8-a3bd-d46b1a312aa0">
 
 Even when I try to do vendor publish it does not work due the same issue.
 
 
<img width="782" alt="image" src="https://github.com/longhornopen/laravel-celtic-lti/assets/17262977/bc7e5be8-1570-41d4-abfc-dd36ff104d78">

manual copy/paste of lti.php config fixes it, but I think it should have some sort of fallback if the configuration is not present.

**Comment by chrispittman** [comment]
Confirmed.  It looks like this is new as of Laravel 11.

**Comment by chrispittman** [comment]
This should be fixed in v1.0.4.
