### ISSUE TITLE
Laravel 11, use internal API as DataConnector

### ISSUE THREAD

**Issue by funkywaddle** [longhornopen/laravel-celtic-lti#28]
I am currently using Laravel 11. 

I have installed your package per your instructions, but am having issues trying to modify it to use API calls as the DataConnector access. Can we just add our own DataConnector class using a home-built API caller?

I want the LTI functionality to happen on this server, but to make calls to an internal API server for the LTI library's basic CRUD operations that exist in the DataConnector class (loadPlatform, savePlatform, loadResourceLink, saveResourceLink, loadPlatformNonce, etc).

What is the best way to approach this?

**Comment by chrispittman** [comment]
I haven't tried that myself, but offhand I don't see a reason why it wouldn't work.  Making a custom DataConnector subclass is probably the way I'd be approaching it too.

**Comment by funkywaddle** [comment]
Me and a co-worker are having issues modifying pretty much anything, because the built-in service provider seems to be instantiating the singleton without a `$dataConnector` being passed in, so when we try to build our own, it bypasses instantiation due to it already being loaded.

So, pretend I'm new to Laravel, can you describe the process to implement a new DataConnector, and use it in the LTITool?

**Comment by chrispittman** [comment]
Personally, in this case I'd just skip the singleton provided by `LtiTool::getLtiTool()`, and just call the `LtiTool()` constructor directly.  That'd give you an LtiTool object which you can build as you see fit.  You can pass that object around as a function parameter, or build your own singleton class to contain it as you see fit.  Your use case is a little off the rails from what the underlying CelticLTI library expects, and this'd insulate you from future changes in either it or this library.

Making a new DataConnector subclass sounds like it'd be fairly straightforward; check https://github.com/longhornopen/LTI-PHP/tree/master/src/DataConnector for the source of that class and its existing subclasses if you need it.

Neither of these should require any Laravel knowledge in particular, but if there are parts that you're finding problematic, let us know and we'll help where we can!

**Comment by chrispittman** [comment]
v1.1.0 might help with this.  There are two new options in the config file, one of which allows you to supply your own custom DataConnector object, which will be used throughout.
