### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by MarcosCifu** [longhornopen/laravel-celtic-lti#3]
Hello, I am trying to make a small integration of an app with LTI 1.3 in Moodle but I have not been able to achieve it, could you give me a hand?

**Comment by chrispittman** [comment]
What, exactly, do you need help with?

**Comment by MarcosCifu** [comment]
I'm trying to integrate this library with Laravel using the rating app but I can't save the basic information of the platform
image
![image](https://user-images.githubusercontent.com/8668878/150002980-8ee20f2d-0d60-48a9-8bd0-f83658a7f47c.png)
I would be very grateful if you could guide me

**Comment by chrispittman** [comment]
Take a look at https://github.com/longhornopen/laravel-celtic-lti/blob/5ab144818cc362f34bd62f55473b567b7740f2eb/src/LtiTool.php#L17-L18 for an example of how to set up a DataConnector with the database you're already using for your Laravel app.

If that doesn't fix it, are you getting an error message?  What does the message say?

**Comment by MarcosCifu** [comment]
Thank you very much, with the definition of pdo I was able to save the platform data, would you have an example of a tool that can connect with moodle?

**Comment by chrispittman** [comment]
As far as I know, you'd be the first to try this library with Moodle.  Let us know what you find!
