### ISSUE TITLE
Bad request: Invalid lti_message_hint

### ISSUE THREAD

**Issue by treyseals** [longhornopen/laravel-celtic-lti#33]
Receiving an "Invalid lti_message_hint" error after being forced to open a new tab.

**Comment by chrispittman** [comment]
Gonna need more info if you want help.  For starters, which LMS are you seeing this error with?

**Comment by treyseals** [comment]
That's my bad @chrispittman ! Canvas LMS. I actually got it to work after using the direct authorize location (from https://canvas.instructure.com/api/lti/authorize_redirect to canvas.{{domain}}).
